version: "3"

services:

  runtime-setup:
    image: swift-nio:18.04-5.0
    build:
      args:
        ubuntu_version: "18.04"
        swift_version: "5.0"
        skip_ruby_from_ppa: "true"

  unit-tests:
    image: swift-nio:18.04-5.0
    command: /bin/bash -cl "swift test -Xswiftc -warnings-as-errors"

  integration-tests:
    image: swift-nio:18.04-5.0
    environment:
      - MAX_ALLOCS_ALLOWED_1000_reqs_1_conn=31200
      - MAX_ALLOCS_ALLOWED_1_reqs_1000_conn=1155050 # was: 685050
      - MAX_ALLOCS_ALLOWED_ping_pong_1000_reqs_1_conn=4600
      - MAX_ALLOCS_ALLOWED_bytebuffer_lots_of_rw=2100
      - MAX_ALLOCS_ALLOWED_future_lots_of_callbacks=99100
      - MAX_ALLOCS_ALLOWED_scheduling_10000_executions=20150

  test:
    image: swift-nio:18.04-5.0
    command: /bin/bash -cl "swift test -Xswiftc -warnings-as-errors && ./scripts/integration_tests.sh"
    environment:
      - MAX_ALLOCS_ALLOWED_1000_reqs_1_conn=31200
      - MAX_ALLOCS_ALLOWED_1_reqs_1000_conn=1155050 # was: 685050
      - MAX_ALLOCS_ALLOWED_ping_pong_1000_reqs_1_conn=4600
      - MAX_ALLOCS_ALLOWED_bytebuffer_lots_of_rw=2100
      - MAX_ALLOCS_ALLOWED_future_lots_of_callbacks=99100
      - MAX_ALLOCS_ALLOWED_scheduling_10000_executions=20150

  echo:
    image: swift-nio:18.04-5.0

  http:
    image: swift-nio:18.04-5.0
